BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_mile
            text: ''
            font_size: 42
        BoxLayout:
            orientation: 'vertical'
#            size_hint_x: 0.25
            Button:
                text: 'Up'
                font_size: 46
            Button:
                text: 'Down'
                font_size: 46